### ISSUE TITLE
Change theme

### ISSUE THREAD

**Issue by nylen** [ClassicPress/site-docs#2]
https://gitea.chriswiegman.com/chriswiegman/chriswiegman-theme

Very simple :heavy_check_mark: 
Has an on-page menu :heavy_check_mark:

**Comment by joyously** [comment]
It might be a little _too_ simple.
If you do use it, you need to add a background color to the body. This is what I see, with my browser default color set to yellow:
![Hello WordPress, My Old Friend - Chris Wiegman-12](https://user-images.githubusercontent.com/7957680/91066018-c9e27b00-e5f6-11ea-9b9a-5464dd105030.jpg)

**Comment by KTS915** [comment]
Now here: https://github.com/ChrisWiegman/chriswiegman-theme

Would be good to do that because we now definitely need a menu!

**Comment by nylen** [comment]
This has been done. Navigation on the docs site is now much better thanks to @TukuToi. If we still need a menu then let's create a separate issue for that.

**Comment by smileBeda** [comment]
Just for reminder in case this comes up later again, changing the theme means massive work. This is not just a theme - if we look at the code, at least the partial parsing mechanism and the search are quite some work to re-implement.

**Comment by joyously** [comment]
> changing the theme means massive work

Ha ha! This is such a good example of why themes should **only** style, not add functionality.
