### ISSUE TITLE
Change breadcrumb script

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/site-docs#4]
See https://forums.classicpress.net/t/missing-breadcrumb-item-on-docs-site-when-searching/3346

The site is currently using an old Justin Tadlock script, which he himself has has since reimagined at https://github.com/themehybrid/hybrid-breadcrumbs as a “as a better drop-in package for theme authors to use.” I suggest we take him at his word and give the updated script a try.

**Comment by viktorix** [comment]
New breadcrumbs have been implemented and are live now.
